version: "3.9"

services:
  wordpress:
    image: wordpress:6.5-apache
    environment:    
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_NAME: wp
      WORDPRESS_CONFIG_EXTRA: |
        if (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
          $_SERVER['HTTPS'] = 'on';
        }

        if (!empty($_SERVER['HTTP_X_FORWARDED_HOST'])) {
          $_SERVER['HTTP_HOST'] = $_SERVER['HTTP_X_FORWARDED_HOST'];
        }
    ports:
      - "80:80"
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: rootpass   # ← ここで root パスワードを固定
      MYSQL_DATABASE: wp              # ← WordPress が使うデータベース
      MYSQL_USER: wp                  # ← WordPress が使うユーザー
      MYSQL_PASSWORD: wp              # ← WordPress が使うパスワード
    volumes:
      - db_data:/var/lib/mysql
      services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db # WordPressのデータベースサービス名
      PMA_PORT: 3306 # WordPressのデータベースポート

volumes:
  db_data:
